#!/usr/bin/env bash
# install-gui.sh — install the host GUI + tray icon for the current desktop user.
#
# Run as the DESKTOP USER, not root: everything lands under $HOME and the
# autostart entry must belong to the session that will run it.
#
#   ./gui/install-gui.sh
#
# Idempotent: re-running replaces the installed copy and rewrites the launcher
# and both .desktop files.
#
# PySide6 comes from the distro packages when they exist (v2 plan D18); the
# fallback is a dedicated venv. `pip install --user` and
# `--break-system-packages` are deliberately never used — they break PEP 668
# systems and are not repairable by this script.
set -euo pipefail

if [ "$(id -u)" -eq 0 ]; then
  echo "Run this as your desktop user, not root — it installs into \$HOME." >&2
  exit 1
fi

here="$(cd "$(dirname "$0")" && pwd)"
APP_DIR="$HOME/.local/share/icloud-bridge-gui"
BIN_DIR="$HOME/.local/bin"
LAUNCHER="$BIN_DIR/icloud-bridge-gui"
DESKTOP_DIR="$HOME/.local/share/applications"
AUTOSTART_DIR="$HOME/.config/autostart"
ICON="$APP_DIR/icloud_bridge_gui/icons/icloud-green.svg"
VENV="$APP_DIR/venv"

# --- 1. copy the package ------------------------------------------------------
echo "==> Installing the application into $APP_DIR"
mkdir -p "$APP_DIR" "$BIN_DIR" "$DESKTOP_DIR" "$AUTOSTART_DIR"
rm -rf "$APP_DIR/icloud_bridge_gui"
cp -r "$here/icloud_bridge_gui" "$APP_DIR/icloud_bridge_gui"
find "$APP_DIR/icloud_bridge_gui" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true

# --- 2. make sure PySide6 is importable --------------------------------------
PYTHON="python3"
if python3 -c 'import PySide6' >/dev/null 2>&1; then
  echo "==> PySide6 already available for $(command -v python3)"
elif command -v apt-get >/dev/null 2>&1; then
  echo "==> Installing the distro PySide6 packages (sudo required)"
  if sudo apt-get install -y \
      python3-pyside6.qtwidgets python3-pyside6.qtgui \
      python3-pyside6.qtcore python3-pyside6.qtsvg; then
    :
  else
    echo "==> Distro packages unavailable; falling back to a dedicated venv"
    python3 -m venv "$VENV" 2>/dev/null || {
      echo "python3-venv is missing; installing it (sudo required)"
      sudo apt-get install -y python3-venv
      python3 -m venv "$VENV"
    }
    "$VENV/bin/pip" install --upgrade pip
    "$VENV/bin/pip" install PySide6
    PYTHON="$VENV/bin/python"
  fi
  if [ "$PYTHON" = "python3" ] && ! python3 -c 'import PySide6' >/dev/null 2>&1; then
    echo "==> Distro packages installed but PySide6 still does not import; using a venv"
    python3 -m venv "$VENV"
    "$VENV/bin/pip" install --upgrade pip
    "$VENV/bin/pip" install PySide6
    PYTHON="$VENV/bin/python"
  fi
else
  echo "==> No apt-get on this system; creating a dedicated venv"
  python3 -m venv "$VENV"
  "$VENV/bin/pip" install --upgrade pip
  "$VENV/bin/pip" install PySide6
  PYTHON="$VENV/bin/python"
fi

if [ "$PYTHON" = "python3" ]; then
  PYTHON="$(command -v python3)"
fi

# --- 3. launcher --------------------------------------------------------------
echo "==> Writing $LAUNCHER"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Generated by gui/install-gui.sh — do not edit; re-run the installer instead.
cd "$APP_DIR"
exec "$PYTHON" -m icloud_bridge_gui "\$@"
EOF
chmod 755 "$LAUNCHER"

# --- 4. desktop entries -------------------------------------------------------
echo "==> Writing desktop entries"
sed -e "s|__LAUNCHER__|$LAUNCHER|" -e "s|__ICON__|$ICON|" \
  "$here/icloud-bridge-gui.desktop" > "$DESKTOP_DIR/icloud-bridge-gui.desktop"

# Preserve a deliberately-disabled autostart choice across upgrades (v2 plan
# D29): if the operator unticked "Start when the computer starts", the installed
# entry carries Hidden=true / X-GNOME-Autostart-enabled=false. Re-running the
# installer rewrites the absolute Exec path but must not silently re-enable it.
AUTOSTART_DST="$AUTOSTART_DIR/icloud-bridge-tray.desktop"
keep_disabled=false
if [ -f "$AUTOSTART_DST" ] \
   && grep -qiE '^(Hidden=true|X-GNOME-Autostart-enabled=false)' "$AUTOSTART_DST"; then
  keep_disabled=true
fi
sed -e "s|__LAUNCHER__|$LAUNCHER|" -e "s|__ICON__|$ICON|" \
  "$here/autostart/icloud-bridge-tray.desktop" > "$AUTOSTART_DST"
if [ "$keep_disabled" = true ]; then
  echo "==> Preserving your disabled autostart choice"
  sed -i 's/^X-GNOME-Autostart-enabled=true/X-GNOME-Autostart-enabled=false/' "$AUTOSTART_DST"
  grep -q '^Hidden=' "$AUTOSTART_DST" || echo 'Hidden=true' >> "$AUTOSTART_DST"
fi
chmod 644 "$DESKTOP_DIR/icloud-bridge-gui.desktop" "$AUTOSTART_DST"

echo
echo "Installed. Start it now with:  $LAUNCHER"
case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) echo "Note: $BIN_DIR is not on your PATH; the desktop entries use the full path anyway." ;;
esac
echo
echo "GNOME users: install the 'AppIndicator and KStatusNotifierItem Support'"
echo "extension for the tray icon to be visible."
